# version: '3'

services:
    db:
        container_name: rdstation-db
        image: postgres:16-alpine
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
            - '5432:5432'
        volumes:
            - postgres13:/var/lib/postgresql/data
        networks:
            - aplication-networks
    redis:
        container_name: rdstation-redis
        image: redis:7.0.15-alpine
        ports:
        - '6379:6379'
        volumes:
        - redis_data:/data
        networks:
            - aplication-networks
    web:
        container_name: rdstation-app
        build: .
        image: rdstation-app
        volumes:
            - .:/rails
        ports:
            - '3000:3000'
        depends_on:
            - db
            - redis
        environment:
            DATABASE_URL: postgresql://postgres:password@db:5432/store_development
            REDIS_URL: redis://redis:6379/0
        networks:
            - aplication-networks
    test:
        build: .
        command: bundle exec rspec
        volumes:
            - .:/rails
        depends_on:
            - db
            - redis 
        environment:
            DATABASE_URL: postgresql://postgres:password@db:5432/store_test
            REDIS_URL: redis://redis:6379/0
        networks:
            - aplication-networks
volumes:
    postgres13:
    redis_data:
networks:
    aplication-networks: